### ISSUE TITLE
Rails: git push heroku master Error 

### ISSUE THREAD

**Issue by fmoudoute** [ruby/stringio#5]
Hi, i am trying to deploy my rails app to Heroku and have the following error: 

`
remote:        Installing rserve-simpler 0.0.6
remote:        Fetching turbolinks 5.2.0
remote:        Installing turbolinks 5.2.0
remote:        Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
remote:        
remote:        current directory:
remote:        /tmp/build_eeba6ab46283f21d52e58c97c0ad1e42/vendor/bundle/ruby/2.4.0/gems/stringio-0.0.1
remote:        /tmp/build_eeba6ab46283f21d52e58c97c0ad1e42/vendor/ruby-2.4.4/bin/ruby -r
remote:        ./siteconf20180925-253-16gsueq.rb extconf.rb
remote:        creating Makefile
remote:        
remote:        current directory:
remote:        /tmp/build_eeba6ab46283f21d52e58c97c0ad1e42/vendor/bundle/ruby/2.4.0/gems/stringio-0.0.1
remote:        make "DESTDIR=" clean
remote:        
remote:        current directory:
remote:        /tmp/build_eeba6ab46283f21d52e58c97c0ad1e42/vendor/bundle/ruby/2.4.0/gems/stringio-0.0.1
remote:        make "DESTDIR="
remote:        make: *** No rule to make target '/include/ruby.h', needed by 'stringio.o'. 
remote:        Stop.
remote:        
remote:        make failed, exit code 2
remote:        
remote:        Gem files will remain installed in
remote:        /tmp/build_eeba6ab46283f21d52e58c97c0ad1e42/vendor/bundle/ruby/2.4.0/gems/stringio-0.0.1
remote:        for inspection.
remote:        Results logged to
remote:        /tmp/build_eeba6ab46283f21d52e58c97c0ad1e42/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0-static/stringio-0.0.1/gem_make.out
remote:        
remote:        An error occurred while installing stringio (0.0.1), and Bundler cannot
remote:        continue.
remote:        Make sure that `gem install stringio -v '0.0.1'` succeeds before bundling.
remote:        
remote:        In Gemfile:
remote:          stringio
remote: 
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to secure-anchorage-42815.
remote: 
To https://git.heroku.com/secure-anchorage-42815.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/secure-anchorage-42815.git'
Lins-MBP:ir3 titi$ gem install stringio -v '0.0.1'
Fetching: stringio-0.0.1.gem (100%)
Building native extensions. This could take a while...
ERROR:  Error installing stringio:
	ERROR: Failed to build gem native extension.

    current directory: /Users/titi/.rvm/gems/ruby-2.5.0/gems/stringio-0.0.1
/Users/titi/.rvm/rubies/ruby-2.5.0/bin/ruby -r ./siteconf20180925-36783-nqzd6j.rb extconf.rb
creating Makefile

current directory: /Users/titi/.rvm/gems/ruby-2.5.0/gems/stringio-0.0.1
make "DESTDIR=" clean

current directory: /Users/titi/.rvm/gems/ruby-2.5.0/gems/stringio-0.0.1
make "DESTDIR="
make: *** No rule to make target `/include/ruby.h', needed by `stringio.o'.  Stop.

make failed, exit code 2
`

All the responses that I found so far are not very clear. Can someone help me please? i followed https://www.codecademy.com/articles/deploy-rails-to-heroku i am on Rails 5.1 on MacOS

**Comment by hsbt** [comment]
You don't need to add `stringio` in your Gemfile. And This repository is the development resource, not FAQ support. 

https://stackoverflow.com/ helps you.

**Comment by fmoudoute** [comment]
I came here because nobody is helping on Stack, and I do need to find a soution @hsbt.

**Comment by stomar** [comment]
@hsbt wrote:
> You don't need to add stringio in your Gemfile.

It's not necessary here, but nevertheless I think you should be able to do so, at least eventually (or gemification of libraries doesn't make sense).

I encounter the same error by simply trying

```
gem install stringio
```

The native extension fails to build. So IMO it's absolutely appropriate to open an issue in this repo.

**Comment by hsbt** [comment]
@stomar ok, I just pushed stringio-0.0.2.
