### ISSUE TITLE
Bundler Version Issues 3.0.5 vs 3.0.6

### ISSUE THREAD

**Issue by daBee** [ruby/stringio#51]
Not sure why this is happening.  Tried to get `3.0.5` through the `Gemfile`, and it grabbed `3.0.6`.  But here is the issue:

```
Could not find stringio-3.0.5 in any of the sources (Bundler::GemNotFound)
```

**Comment by kou** [comment]
Could you provide a reproducible example?

**Comment by daBee** [comment]
Sorry, I cannot.

**Comment by daBee** [comment]
From Gemfile.lock:

```
open-uri (0.3.0)
  stringio
  time
  uri
(snip)
stringio (3.0.6)
(snip)
BUNDLED WITH
   2.4.12
```

**Comment by kou** [comment]
Sorry. We can't help you without a reproducible example.
