### ISSUE TITLE
v3.1.0 not available from rubygems.org

### ISSUE THREAD

**Issue by colinbruce** [ruby/stringio#73]
Dependabot has opened PRs on multiple repos for v3.1.0 this morning but none of them are successful.

Locally running: `gem install stringio -v 3.1.0` or `gem install stringio -v 3.1`
Results in 
```shell
ERROR:  Could not find a valid gem 'stringio' (= 3.1) in any repository
ERROR:  Possible alternatives: stringio
```

Attempting `bundle update stringio` manually returns:
```shell
Bundler attempted to update stringio but its version stayed the same
```

`gem list stringio --remote --all`
returns
```shell
*** REMOTE GEMS ***

rubysl-stringio (2.3, 2.2, 2.1, 2.1.0, 2.0.0, 1.0.1, 1.0.0)
stringio (3.1.0 ruby java, 3.0.9 ruby java, 3.0.8 ruby java, 3.0.7 ruby java, 3.0.6 ruby java, 3.0.5 ruby java, 3.0.4 ruby java, 3.0.3 ruby java, 3.0.2 ruby java, 3.0.1, 3.0.0, 0.1.4, 0.1.3, 0.1.0, 0.0.2, 0.0.1)
```
Other gems are updating. Is this an issue with rubygems or do you need to republish?

**Comment by kou** [comment]
@hsbt Could you check rubygems.org side?
FYI: I got some Unicorn errors when I push stringsio 3.1.0 gems. I re-pushed.

**Comment by colinbruce** [comment]
Yeah, it's like it's created the DB entry for it but not stored the actual gem 😕  🤷‍♂️

**Comment by junaruga** [comment]
In my environment, I can install the stringio gem version 3.1.0 now.

```
$ which ruby
~/.local/ruby-3.3.0dev-debug-ced84beb25/bin/ruby

$ ruby -v
ruby 3.3.0dev (2023-11-07T10:22:30Z master ced84beb25) [x86_64-linux]

$ which gem
~/.local/ruby-3.3.0dev-debug-ced84beb25/bin/gem

$ gem -v
3.5.0.dev

$ gem list | grep stringio
stringio (default: 3.0.9)

$ gem install stringio -v 3.1.0
Building native extensions. This could take a while...
Successfully installed stringio-3.1.0
Parsing documentation for stringio-3.1.0
Installing ri documentation for stringio-3.1.0
Done installing documentation for stringio after 0 seconds
1 gem installed

$ gem list | grep stringio
stringio (3.1.0, default: 3.0.9)
```

**Comment by hsbt** [comment]
I and @mame ping to rubygems team for this on their official slack. We should move to https://github.com/rubygems/rubygems.org/issues/4247.

**Comment by simi** [comment]
> @hsbt Could you check rubygems.org side? FYI: I got some Unicorn errors when I push stringsio 3.1.0 gems. I re-pushed.

That seems to explain the problem. There was small partial downtime at the time causing errors and gem ingestion hasn't finished. I have fixed the release on RubyGems.org side and 3.1.0 appears properly in `/info/stringio` again. Sorry for the troubles.

**Comment by hsbt** [comment]
@simi Thanks always ❤️
