### ISSUE TITLE
Appending text to initialized StringIO instance

### ISSUE THREAD

**Issue by throwaway-account-1** [ruby/stringio#8]
Hello,

I'm not sure if this is a bug or a feature mimicking one-way IO, but I got a bit confused with this functionality:

Initializing an empty StringIO instance with _no constructor parameters_ allows me to read-from and write-to it:

```ruby
a = StringIO.new
a << 'test'
a << 'test'
a.string # => "testtest"
```

But then when I use the _constructor to initialise an initial value_ it becomes read-only:

```ruby
b = StringIO.new 'test'
b << 'test'
b.string # => "test"
```

I would assume this should also result in `"testtest"` but I might be wrong. It looks like when I create a StringIO instance and initialise it using the constructor it becomes read-only. Is this intentional?

Also I couldn't find any documentation on the `<<` operator in regards to StringIO so maybe I shouldn't be using it?

Sorry about the inconvenience

Extra info:

```sh
$ gem list | grep stringio
stringio (default: 0.1.0)
```

**Comment by nobu** [comment]
Probably you have `frozen-string-literal` pragma in the source and pass a frozen string literal.
In that case, the `StringIO` instance is read-only.
